# Configuration file for the Sphinx documentation builder.
#
# This file only contains a selection of the most common options. For a full
# list see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
# import os
# import sys
# sys.path.insert(0, 'C:\\Users\\ryoka\\Desktop\\sample_module\\sample_module')


# -- Project information -----------------------------------------------------

project = 'sample_module'
copyright = '2021, Author'
author = 'Author'


# -- General configuration ---------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.napoleon',
    'sphinx.ext.viewcode',
    'sphinx.ext.todo',
]

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = 'en'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']


# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = 'alabaster'

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']


# -- Extension configuration -------------------------------------------------
html_theme = 'sphinx_rtd_theme'
# -- Options for todo extension ----------------------------------------------

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = True

latex_documents = [
    ('indexpdf', 'index.rst', project, author, 'manual', True),
]
latex_elements = {
    'papersize': 'a4paper',
    'figure_align': 'H',
    'preamble': r'''
       \geometry{top=1.5cm, bottom=1cm, left=1cm, right=1cm, includefoot}
       \usepackage{titlesec}
       \titleclass{\chapter}{top}
       \titleformat{\chapter}
         [display]  % shape
         {\centering\normalfont\huge\bfseries} % format
         {\titlerule[5pt]\vspace{3pt}\titlerule[2pt]\vspace{1em}} % laberl
         {0pt} % sep
         {\vspace{3pt}\Huge} % before-code
         % code
         [{\vspace{1em}\titlerule[2pt]\vspace{3pt}\titlerule[5pt]}] % after-code

       \titleformat{\section}[block]
         {\normalfont\huge\bfseries} % format
         {\thesection.} % label
         {0.5em} % sep
         {\vspace{3pt}\huge} % before-code
         [{\vspace{2pt}\titlerule[2pt]}] % after-code

       \setcounter{secnumdepth}{2}
       \setcounter{tocdepth}{2}

       \usepackage{hyperref}
       \usepackage{pxjahyper}

       \hypersetup{bookmarksnumbered}
     '''
}
latex_show_urls = 'footnote'
latex_use_xindy = True
latex_show_pagerefs = True
